stages:
  - build

build:
  stage: build
  image: sacurio/debianpackager:0.2
  before_script:
    - 'apt-get update && apt-get install -y --no-install-recommends golang-golang-x-crypto-dev golang-golang-x-net-dev'
  script:
    - gbp buildpackage --git-ignore-branch
  artifacts:
    paths:
      - '../*.deb'
      - '../*.dsc'
      - '../*.changes'
      - '../*.tar.xz'